-- Disable RLS on all tables to allow public anonymous read and write operations
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE payables DISABLE ROW LEVEL SECURITY;
ALTER TABLE pdcs DISABLE ROW LEVEL SECURITY;
ALTER TABLE loan_schedule DISABLE ROW LEVEL SECURITY;
ALTER TABLE vendors DISABLE ROW LEVEL SECURITY;
ALTER TABLE employees DISABLE ROW LEVEL SECURITY;
